[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"
hooks = [
  { id = "trailing-whitespace", args = ["--markdown-linebreak-ext=md"], groups = ["ci"] },
  { id = "end-of-file-fixer", groups = ["ci"] },
  { id = "check-added-large-files", groups = ["ci"] },
  { id = "check-case-conflict", groups = ["ci"] },
  { id = "check-illegal-windows-names", groups = ["ci"] },
  { id = "check-merge-conflict", groups = ["ci"] },
  { id = "mixed-line-ending", groups = ["ci"] },
  { id = "check-toml", groups = ["ci"] },
  { id = "check-yaml", files = "\\.(yml|yaml)$", groups = ["ci"] },
]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.21"
hooks = [
  { id = "ruff-check", args = ["--fix"] },
  { id = "ruff-format" },
]

[[repos]]
repo = "https://github.com/DetachHead/basedpyright-prek-mirror"
rev = "1.39.9"
hooks = [
  { id = "basedpyright" },
]
